apiVersion: v1
kind: Pod
metadata:
  name: dev-apache
  labels:
    app: dev
spec:
  containers:
  - name: boxone
    image: docker.io/lovelearnlinux/webserver:v1
    volumeMounts:
      - name: web-config
        mountPath: /etc/httpd/conf/
      - name: web-page
        mountPath: /var/www/html/
  volumes:
    - name: web-config
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: dev-apache-config
    - name: web-page
      configMap:
        name: dev-webpage
