apiVersion: v1
kind: Pod
metadata:
  name: devone
  labels:
    app: devone
spec:
  containers:
  - name: boxone
    image: docker.io/library/mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
#          name: sqlcreds --- literal based configuration
          name: mysql-creds #File based configuration
          key: password
#  imagePullSecrets:
#    - name: my-registry-secret
